# A unique session name
session_name: 'madCore__'

# The life time of the cookie in seconds
lifetime: 0

# The path where the information is stored
path: '/'

# The domain that the cookie belongs to
domain : ''

# The cookie should be only sent over secure connections 
secure: false

# The cookie can only be accessed through http connection
httponly: true

# Control of cross-site sending of the cookie
# supports lax-strict-none-null
samesite: lax

# Specify the time in seconds which after data will be seen
# as 'garbage' and potentially cleaned up
gc_maxlifetime: '1800'

# In conjunction with session.gc_divisor is used to manage probability that 
# the garbage collection routine is started
gc_probability: '1000'

# Coupled with session.gc_probability defines the probability that the garbage collection
# process is started on every intiallization 
#The probability is calculated by using gc_probability/gc_divisor, e.g. 1/100 means there 
# is a 1% chance that the GC process starts on each request. session.gc_divisor defaults to 100
gc_divisor: '1'

# Specify whether the module will use cookiesto store the session id on the client side 
# Defaults to 1 "enabled"
use_cookies: '1'


# cookie_lifetime: '1'